import type { RuleMetadata } from '../../api.js';

export const DDL_RULES: readonly RuleMetadata[] = [
  {
    id: 'DDL_EMPTY_LINES_WITHIN',
    displayName: 'Standardize empty lines within sections',
    description: 'Currently only caps consecutive blank lines to at most one and trims blank lines at document end; does not yet classify DDL sections (parameters, joins, associations, select list).',
    groupId: 'DDL_EMPTY_LINES',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlEmptyLinesWithinSectionsRule',
    settings: [],
  },
  {
    id: 'DDL_SPACES_AROUND_SIGNS',
    displayName: 'Standardize spaces around colon, comma etc.',
    description: 'Currently standardizes comma spacing and //-- line-end comment marker spacing only; colon and arithmetic-operator spacing are not yet handled.',
    groupId: 'DDL_SPACES',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlSpacesAroundSignsRule',
    settings: [],
  },
  {
    id: 'DDL_SPACES_AROUND_BRACKETS',
    displayName: 'Standardize spaces around brackets',
    description: 'Currently standardizes spacing around [ ] cardinality and path-expression brackets only; parentheses ( ) for functions, ABAP types, and arithmetics are not yet handled.',
    groupId: 'DDL_SPACES',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlSpacesAroundBracketsRule',
    settings: [],
  },
  {
    id: 'DDL_POSITION_BRACES',
    displayName: 'Break before select list braces',
    description: 'Currently only enforces a line break with no indent before the opening and closing brace of each top-level select list; configurable break modes/indents and the legacy brace-less SELECT...FROM syntax are not yet handled.',
    groupId: 'DDL_POSITION',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlPositionBracesRule',
    settings: [],
  },
  {
    id: 'DDL_POSITION_CLAUSES',
    displayName: 'Break before WHERE clause etc.',
    description: 'Currently only enforces a line break with no indent before top-level WHERE, HAVING, GROUP BY, UNION [ALL], INTERSECT, and EXCEPT keywords, condensing a split GROUP BY/UNION ALL phrase onto one line; forcing an extra blank line before UNION/INTERSECT/EXCEPT and re-indenting a multi-line condition after its keyword moves are not yet handled.',
    groupId: 'DDL_POSITION',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlPositionClausesRule',
    settings: [],
  },
  {
    id: 'DDL_POSITION_SELECT',
    displayName: 'Break before AS SELECT etc.',
    description: 'Currently only enforces a line break with indent 2 before "AS SELECT [DISTINCT] FROM", "AS PROJECTION ON", and "{EXCEPT|INTERSECT|UNION [ALL]} SELECT [DISTINCT] FROM", condensing each phrase onto one line; breaking before the data source and the extra blank line after WITH PARAMETERS (...) are not yet handled.',
    groupId: 'DDL_POSITION',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlPositionSelectRule',
    settings: [],
  },
  {
    id: 'DDL_POSITION_DEFINE',
    displayName: 'Break before DEFINE etc.',
    description: 'Currently only enforces a line break with no indent before the first top-level DEFINE/EXTEND/ANNOTATE keyword, condensing the following structural-keyword phrase up to the entity name (via a fixed keyword list, not full entity-name pattern matching) onto one line, and breaks before a top-level WITH PARAMETERS at indent 2, condensing that phrase; joining an already-broken entity name, forcing a blank line before DEFINE/EXTEND/ANNOTATE, re-indenting each parameter, and ROLE/ACCESSPOLICY declarations are not yet handled.',
    groupId: 'DDL_POSITION',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlPositionDefineRule',
    settings: [],
  },
  {
    id: 'DDL_EMPTY_LINES_BETWEEN',
    displayName: 'Standardize empty lines between sections',
    description: 'Currently only enforces at least one blank line between trailing annotations and DEFINE/EXTEND/ANNOTATE, before/after the select list braces, and no blank line directly after { or before }, without ever creating a break where none exists; the boundaries around JOIN, ASSOCIATION, and WITH PARAMETERS (...) are not yet handled.',
    groupId: 'DDL_EMPTY_LINES',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlEmptyLinesBetweenSectionsRule',
    settings: [],
  },
  {
    id: 'DDL_ANNO_LAYOUT',
    displayName: 'Standardize annotation layout',
    description: 'Currently only condenses an annotation\'s dotted path onto one contiguous run with no internal whitespace and standardizes spacing around every colon (no space before, one space after, unless already followed by a line break); nesting depth/order, one-liner detection, value/table alignment, and inner brace/bracket spacing are not yet handled.',
    groupId: 'DDL_ANNOTATIONS',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlAnnotationLayoutRule',
    settings: [],
  },
  {
    id: 'DDL_ANNO_NESTING',
    displayName: 'Rearrange annotations',
    description: 'Currently nests a run of 5 or more CONSECUTIVE simple annotations (@path: single-token-value, no existing {}/[] structure, no trailing comment) sharing an exact parent path of 3 or more segments into one @parentPath: { name: value, ... } annotation, always written multi-line (never collapsed to one line, matching default behavior only for runs at or above the 5-member threshold where a one-liner is never a candidate regardless of width) with member names column-padded and continuation lines hanging-indented to the brace column. Fewer than 5 siblings, a parent path shorter than 3 segments, a gap (blank line or comment) between candidates, non-adjacent same-prefix annotations, deeper nesting, and all sort-order/empty-line/allow-block-list configuration are not recognized.',
    groupId: 'DDL_ANNOTATIONS',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlAnnotationNestingRule',
    settings: [],
  },
  {
    id: 'DDL_POSITION_JOIN',
    displayName: 'Break before JOINs',
    description: 'Currently enforces a line break at indent 4 before every top-level JOIN keyword phrase, condensing it onto one line, and forces a break before ON at indent 6 for every JOIN in the file if any of them already has a multi-line condition (matching the file-wide default); the WITH DEFAULT FILTER clause, breaking before the data source, and re-indenting a multi-line condition\'s continuation lines are not yet handled.',
    groupId: 'DDL_POSITION',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlPositionJoinRule',
    settings: [],
  },
  {
    id: 'DDL_POSITION_ASSOCIATION',
    displayName: 'Break before ASSOCIATIONs',
    description: 'Currently enforces a line break at indent 2 before every top-level ASSOCIATION/COMPOSITION keyword phrase (including its cardinality bracket), condensing it onto one line, and forces a break before ON at indent 4 for every ASSOCIATION in the file if any of them already has a multi-line condition (matching the file-wide default); the WITH DEFAULT FILTER clause, breaking before the data source, and re-indenting a multi-line condition\'s continuation lines are not yet handled.',
    groupId: 'DDL_POSITION',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlPositionAssociationRule',
    settings: [],
  },
  {
    id: 'DDL_ALIGN_ENTITY_PARAMETERS',
    displayName: 'Align view parameters',
    description: 'Currently enforces indent 4 and left-pads the name/colon columns of a WITH PARAMETERS clause when every parameter has the simple shape <name> : <single-token-type>; an annotation directly above a parameter is left untouched, and a single parameter with a multi-token type (e.g. abap.char( 10 )) cancels alignment for the whole clause rather than misreading it.',
    groupId: 'DDL_ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlAlignEntityParametersRule',
    settings: [],
  },
  {
    id: 'DDL_ALIGN_SOURCE_PARAMETERS',
    displayName: 'Align source parameters',
    description: 'Currently left-pads the name/colon columns of parameters passed to a parameterized data source (select from/join/on Entity( P_Param : value, ... )) when every parameter has the simple shape <name> : <single-token-value> and each is on its own source line; a dotted path like $parameters.P_AnyParam counts as one token, but a multi-token value (e.g. an arithmetic expression) cancels alignment for the whole clause; repositioning the opening parenthesis or the AS <alias> after the closing parenthesis is not yet handled.',
    groupId: 'DDL_ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlAlignSourceParametersRule',
    settings: [],
  },
  {
    id: 'DDL_ALIGN_LOGICAL_EXPRESSIONS',
    displayName: 'Align logical expressions',
    description: 'Currently aligns a flat chain of comparisons in a top-level JOIN/ASSOCIATION ON condition, joined only by AND or only by OR (never mixed), where every comparison uses the same single-token symbolic operator (=, <>, <, >, <=, >=) with a single-token left- and right-hand side and each condition after the first is on its own source line; the ON line itself is left untouched. WHERE/HAVING/WHEN/path-expression-filter conditions, NOT, parentheses, predicate expressions, and mixed operator widths are not recognized.',
    groupId: 'DDL_ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlAlignLogicalExpressionsRule',
    settings: [],
  },
  {
    id: 'DDL_ALIGN_FUNCTION_PARAMETERS',
    displayName: 'Align function parameters',
    description: 'Currently left-pads the name/=> columns of a CDS built-in function call\'s named parameters (e.g. currency_conversion( amount => a, source_currency => b )) when every parameter has the simple shape <name> => <single-token-value> and each is on its own source line; a nested function call aligns independently of its enclosing call. A single parameter with a multi-token value cancels alignment for the whole call rather than skipping just that parameter (stricter than upstream, which skips only the non-matching parameter); repositioning the opening/closing parenthesis is not handled.',
    groupId: 'DDL_ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlAlignFunctionParametersRule',
    settings: [],
  },
  {
    id: 'DDL_ALIGN_FIELD_LISTS',
    displayName: 'Align field lists',
    description: 'Currently forces a GROUP BY field list of 2+ fields onto one field per line, hang-indented to the first field\'s own column, unconditionally (matching upstream\'s default, which does not gate on field complexity or existing one-line layout); a function call\'s internal commas do not split fields. The DDIC-view parenthesized name list (this rule\'s other upstream target), comment re-indentation, and comma-spacing normalization are not handled; the first field\'s own position/indent (upstream\'s GroupByListPos) is not repositioned.',
    groupId: 'DDL_ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlAlignFieldListsRule',
    settings: [],
  },
  {
    id: 'DDL_ALIGN_DATA_SOURCES',
    displayName: 'Align data sources',
    description: 'Currently left-pads the data-source name across a FROM clause and its JOIN/ASSOCIATION phrases so each row\'s AS alias (and, when on the same source line, ON condition) lines up in a shared column; a data source with no alias is not padded itself, but its width still counts toward the shared column. The JOIN/ASSOCIATION keyword phrase itself is not aligned into its own column (already positioned by DDL_POSITION_JOIN/DDL_POSITION_ASSOCIATION); an AS alias or ON condition already on its own separate source line is left untouched rather than merged upward. A run of fewer than 2 data sources, or one whose data source doesn\'t reduce to a simple name (optionally parameterized) plus AS alias, is left untouched.',
    groupId: 'DDL_ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlAlignDataSourcesRule',
    settings: [],
  },
  {
    id: 'DDL_ALIGN_SELECT_LIST',
    displayName: 'Align select list',
    description: 'Currently left-pads each select-list element (a KEY/VIRTUAL prefix, if present, is folded into the element itself rather than its own column) so every element\'s AS alias lines up in a shared column; an element with no alias is not padded itself, but its width still counts toward the shared column. Requires the list to already be one element per line (refuses if any two elements share a source line) and refuses the whole list if any element contains a comment. Forcing a one-element-per-line layout, the DDIC-view name-list-adjacent layout concerns, and any comment-integration behavior are not implemented.',
    groupId: 'DDL_ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlAlignSelectListRule',
    settings: [],
  },
  {
    id: 'DDL_TYPO',
    displayName: 'Correct frequent typos in DDL comments',
    description: 'Currently corrects the same narrow, unambiguous typo-correction table used by the ABAP TYPO rule inside DDL/DCL comments only; adding TODO comments on suspect annotation values and British-to-American conversion are not yet handled.',
    groupId: 'DDL_SPACES',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'DdlTypoRule',
    settings: [],
  },
];
