import type { RuleMetadata } from '../../api.js';

export const SYNTAX_RULES: readonly RuleMetadata[] = [
  {
    id: 'ALIGN_ABAP_DOC',
    displayName: 'Align ABAP Doc',
    description: 'Currently right-pads the keyword and name columns of "! @parameter/@raising/@exception <name> | <text> ABAP Doc lines for a run of more than one such line, stopping at the first non-"!-prefixed token; a run immediately followed by another comment (rather than the declaration it documents) is left untouched.',
    groupId: 'ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'AlignAbapDocRule',
    settings: [],
  },
  {
    id: 'ALIGN_METHODS_REDEFINITION',
    displayName: 'Align METHODS ... REDEFINITION',
    description: 'Currently aligns the METHODS/name columns for a run of at least two consecutive single-line, non-chained METHODS <name> REDEFINITION. statements, using the same alignment engine as ALIGN_ASSIGNMENTS; the FINAL REDEFINITION variant, a chained METHODS: declaration, a trailing comment, and a statement spanning more than one line are not recognized and break the run.',
    groupId: 'ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'AlignMethodsRedefinitionRule',
    settings: [],
  },
  {
    id: 'ALIGN_METHODS_FOR_TESTING',
    displayName: 'Align METHODS ... FOR TESTING',
    description: 'Currently aligns the METHODS/name/FOR columns for a run of at least two consecutive single-line, non-chained METHODS <name> FOR TESTING. statements, using the same alignment engine as ALIGN_ASSIGNMENTS; ABSTRACT, RAISING, a chained METHODS: declaration, a trailing comment, and a statement spanning more than one line are not recognized and break the run.',
    groupId: 'ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'AlignMethodsForTestingRule',
    settings: [],
  },
  {
    id: 'ALIGN_DECLARATIONS',
    displayName: 'Align declarations',
    description: 'Currently aligns DATA/CONSTANTS/FIELD-SYMBOLS declarations of the simple shape <name> TYPE <single-token-type> [VALUE <single-token-value>]. either across a run of at least two consecutive, non-chained declarations sharing the same keyword and VALUE-presence, or independently within one chained declaration; TYPES, BEGIN OF/END OF structures, LIKE, LENGTH/DECIMALS/READ-ONLY, a multi-token VALUE, a trailing comment, and a multi-line declaration are not recognized.',
    groupId: 'ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'AlignDeclarationsRule',
    settings: [],
  },
  {
    id: 'ALIGN_LOGICAL_EXPRESSIONS',
    displayName: 'Align logical expressions',
    description: 'Currently aligns a flat chain of comparisons after IF/ELSEIF/CHECK/WHILE, joined only by AND or only by OR (never mixed), where every comparison uses the same single-character-or-two symbolic operator (=, <>, <, >, <=, >=) with a single-token left- and right-hand side and each condition after the first is on its own source line; the triggering keyword line itself is left untouched. NOT, parentheses, EQUIV, predicate expressions (IS INITIAL/IS BOUND/IN/BETWEEN), keyword-style operators (EQ/NE/...), mixed operator widths, and WHERE/ON/HAVING/WHEN SQL contexts are not recognized.',
    groupId: 'ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'AlignLogicalExpressionsRule',
    settings: [],
  },
  {
    id: 'ALIGN_SELECT_CLAUSES',
    displayName: 'Align SELECT clauses',
    description: 'Currently repositions FROM/WHERE/GROUP BY/HAVING/ORDER BY/INTO/APPENDING onto their own line at SELECT-column+2 for an already-multi-line, single-query OpenSQL SELECT statement (matching the default "keep existing" one-liner policy: an already single-line statement is left untouched); a FROM already glued to the SELECT line with no JOIN is left as-is. UNION/INTERSECT/EXCEPT, subqueries, FOR ALL ENTRIES, %_HINTS, and the SELECT...ENDSELECT loop form are not recognized and refuse the whole statement; no column/value alignment is performed.',
    groupId: 'ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'AlignSelectClausesRule',
    settings: [],
  },
  {
    id: 'ALIGN_SELECT_LISTS',
    displayName: 'Align SELECT lists',
    description: 'Currently repositions a SELECT field list onto one field per line, hang-indented to the first field\'s column, when every field is "complex" (more than one token, e.g. a function call or an AS addition, or a single tilde-qualified token such as t1~col) matching a conservative subset of upstream\'s default classification; a list mixing simple (bare, non-tilde) and complex fields, a single-field list, or an already single-line statement is left untouched. Also left-pads each field\'s name so a trailing AS alias lines up in a shared column across fields (a field with no AS is not padded itself, but its width still counts toward that shared column); a nested AS inside a function call is not mistaken for the field\'s own alias.',
    groupId: 'ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'AlignSelectListsRule',
    settings: [],
  },
  {
    id: 'ALIGN_WITH_SECOND_WORD',
    displayName: 'Align keywords with second word of first line',
    description: 'Currently repositions WITH/INTO/ASSIGNING/WHERE continuation keywords (each starting its own source line) to the column of a READ or LOOP statement\'s own second word (e.g. TABLE in READ TABLE, AT in LOOP AT), when that second word is on the same line as READ/LOOP; AND/OR/EQUIV are never repositioned. An include list of just READ/LOOP is used in place of upstream\'s much longer exclude list, since both are unambiguous internal-table/loop operations with no Open-SQL homonym; other trigger keywords (INSERT/DELETE/MODIFY/EXPORT/IMPORT/SUBMIT/etc.) are not recognized.',
    groupId: 'ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'AlignWithSecondWordRule',
    settings: [],
  },
  {
    id: 'ALIGN_COND_EXPRESSIONS',
    displayName: 'Align conditional expressions',
    description: 'Currently splits a COND #( WHEN ... THEN ... [ELSE ...] ) constructor expression with exactly one WHEN branch onto separate WHEN/THEN/ELSE lines, each hang-indented to WHEN\'s own column, when the expression already spans more than one source line; an already single-line expression is left untouched. SWITCH, a LET ... IN prefix, a multi-WHEN (tabular) expression, and any comment inside the parentheses are not recognized and refuse the whole expression; the THEN/ELSE value content itself is never touched.',
    groupId: 'ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'AlignCondExpressionsRule',
    settings: [],
  },
  {
    id: 'ALIGN_ALIASES_FOR',
    displayName: 'Align ALIASES ... FOR ...',
    description: 'Currently aligns the ALIASES/identifier/FOR columns for a run of at least two consecutive non-chained ALIASES <name> FOR <target>. statements to the widest cell in each column, using the same alignment engine as ALIGN_ASSIGNMENTS; a chained ALIASES: declaration or a statement with a trailing comment is not recognized and breaks the run.',
    groupId: 'ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'AlignAliasesForRule',
    settings: [],
  },
  {
    id: 'ALIGN_CLEAR_FREE_AND_SORT',
    displayName: 'Align CLEAR:/FREE: chains',
    description: 'Currently only breaks a CLEAR: or FREE: chain of plain-identifier items (no additions) onto its own lines, each indented to the column of the first item; SORT ... BY and CATCH chains are not yet handled.',
    groupId: 'ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'AlignClearFreeAndSortRule',
    settings: [],
  },
  {
    id: 'ALIGN_ASSIGNMENTS',
    displayName: 'Align assignments to the same object',
    description: 'Currently right-pads the identifier column and right-aligns the operator column (=, +=, -=, *=, /=, ?=, &&=) for a run of at least two consecutive simple assignments to the same structure variable (the text before an identifier\'s last "-"; a plain identifier with no "-" never groups with anything); the full multi-column AlignTable engine, other alignable command shapes, and the remaining 16 upstream ALIGN_* rules are not yet handled.',
    groupId: 'ALIGNMENT',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'AlignAssignmentsRule',
    settings: [],
  },
  {
    id: 'CAMEL_CASE_IN_CDS_TEST',
    displayName: 'Use CamelCase in test class for CDS view',
    description: 'Currently adds CI_NOWHERE only to exact SELECT statements of the annotated CDS test view.',
    groupId: 'PRETTY_PRINTER',
    defaultEnabled: false,
    essentialEnabled: false,
    docId: 'CamelCaseInCdsTestRule',
    settings: [],
  },
  {
    id: 'IF_BLOCK_AT_LOOP_END',
    displayName: 'Replace long IF blocks at loop end',
    description: 'Currently converts a final single-command IF operand IS INITIAL loop block to an early CONTINUE guard.',
    groupId: 'COMMANDS',
    defaultEnabled: false,
    essentialEnabled: false,
    docId: 'IfBlockAtLoopEndRule',
    settings: [],
  },
  {
    id: 'IF_BLOCK_AT_METHOD_END',
    displayName: 'Replace long IF blocks at method end',
    description: 'Currently converts a final single-command IF operand IS INITIAL block to an early RETURN guard.',
    groupId: 'COMMANDS',
    defaultEnabled: false,
    essentialEnabled: false,
    docId: 'IfBlockAtMethodEndRule',
    settings: [],
  },
  {
    id: 'UPPER_AND_LOWER_CASE',
    displayName: 'Convert upper and lower case',
    description: 'Currently uppercases only recognized standalone statement-leading keywords.',
    groupId: 'PRETTY_PRINTER',
    defaultEnabled: false,
    essentialEnabled: false,
    docId: 'UpperAndLowerCaseRule',
    settings: [],
  },
  {
    id: 'COMMENT_TYPE',
    displayName: 'Comment with " instead of * for prose',
    description: 'Currently converts only unambiguous column-one prose asterisk comments and preserves code-shaped comments.',
    groupId: 'SYNTAX',
    defaultEnabled: false,
    essentialEnabled: true,
    docId: 'CommentTypeRule',
    settings: [],
  },
  {
    id: 'CONDENSE',
    displayName: 'Replace CONDENSE with string function',
    description: 'Currently replaces adjacent declared scalar CONDENSE statements.',
    groupId: 'COMMANDS',
    defaultEnabled: false,
    essentialEnabled: true,
    docId: 'CondenseRule',
    minimumAbapRelease: 702,
    settings: [],
  },
  {
    id: 'STRING_TEMPLATE',
    displayName: 'Use string templates to assemble text',
    description: 'Currently converts safe backtick literal and identifier concatenations in simple assignments.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'StringTemplateRule',
    minimumAbapRelease: 702,
    settings: [],
  },
  {
    id: 'ASSERT_PARAMETER_ORDER',
    displayName: 'Standardize assertion parameter order',
    description: 'Currently places EXP before ACT in two-argument scalar assert_equals calls.',
    groupId: 'COMMANDS',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'AssertParameterOrderRule',
    settings: [],
  },
  {
    id: 'ASSERT_CLASS',
    displayName: 'Use assert class instead of ASSERT',
    description: 'Currently converts simple one-line bound, initial, scalar comparison, ABAP boolean, and sy-subrc ASSERT predicates to a configurable assert class.',
    groupId: 'COMMANDS',
    defaultEnabled: false,
    essentialEnabled: false,
    docId: 'AssertClassRule',
    settings: [{ name: 'assertClassName', description: 'Class called for converted assertions.', type: 'string', defaultValue: 'cx_assert' }],
  },
  {
    id: 'DESCRIBE_TABLE',
    displayName: 'Replace DESCRIBE TABLE ... LINES with lines( )',
    description: 'Currently replaces exact uncommented DESCRIBE TABLE ... LINES statements immediately before RETURN.',
    groupId: 'COMMANDS',
    defaultEnabled: false,
    essentialEnabled: true,
    docId: 'DescribeTableRule',
    settings: [],
  },
  {
    id: 'TRANSLATE',
    displayName: 'Replace TRANSLATE with string functions',
    description: 'Currently replaces adjacent declared scalar TRANSLATE ... TO UPPER or LOWER CASE statements.',
    groupId: 'COMMANDS',
    defaultEnabled: false,
    essentialEnabled: true,
    docId: 'TranslateRule',
    minimumAbapRelease: 702,
    settings: [],
  },
  {
    id: 'TYPO',
    displayName: 'Correct frequent typos',
    description: 'Currently corrects an embedded unambiguous subset of frequent typos in comments only.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'TypoRule',
    settings: [],
  },
  {
    id: 'NEEDLESS_PARENTHESES',
    displayName: 'Remove needless parentheses',
    description: 'Currently removes one outer pair around single-line operand IS INITIAL predicates in selected logical statements.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'NeedlessParenthesesRule',
    settings: [],
  },
  {
    id: 'PRAGMA_POSITION',
    displayName: 'Move pragmas to correct position',
    description: 'Currently moves one complete, uncommented trailing pragma before a statement period.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'PragmaPositionRule',
    settings: [],
  },
  {
    id: 'END_OF_COMMENT',
    displayName: 'Remove end-of comments',
    description: 'Currently removes trailing METHOD, FORM, and FUNCTION end comments that exactly repeat the paired name.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'EndOfCommentRule',
    settings: [],
  },
  {
    id: 'CHECK_IN_LOOP',
    displayName: 'Convert CHECK in loop to IF NOT ... CONTINUE',
    description: 'Currently converts single-line operand IS INITIAL checks in complete LOOP, DO, and WHILE blocks.',
    groupId: 'COMMANDS',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'CheckInLoopRule',
    settings: [],
  },
  {
    id: 'CHECK_OUTSIDE_LOOP',
    displayName: 'Convert CHECK outside loop to IF NOT ... RETURN',
    description: 'Currently converts single-line operand IS INITIAL checks in complete procedures when no loop encloses them.',
    groupId: 'COMMANDS',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'CheckOutsideLoopRule',
    settings: [],
  },
  {
    id: 'EXIT_OUTSIDE_LOOP',
    displayName: 'Replace EXIT outside loop with RETURN',
    description: 'Currently converts bare EXIT statements inside complete methods, functions, and forms when no loop encloses them.',
    groupId: 'COMMANDS',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'ExitOutsideLoopRule',
    settings: [],
  },
  {
    id: 'EQUALS_SIGN_CHAIN',
    displayName: 'Resolve equals sign chain into several commands',
    description: 'Currently splits one-line chains of plain identifiers with a simple final value.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'EqualsSignChainRule',
    settings: [],
  },
  {
    id: 'PSEUDO_COMMENT',
    displayName: 'Replace obsolete pseudo comments with pragmas',
    description: 'Currently converts an embedded unambiguous subset of complete trailing pseudo-comments; requires ABAP 7.02 or later.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'PseudoCommentRule',
    minimumAbapRelease: 702,
    settings: [],
  },
  {
    id: 'RECEIVING_KEYWORD',
    displayName: 'Omit RECEIVING',
    description: 'Currently converts simple one-line method calls with only a simple RECEIVING parameter.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'ReceivingKeywordRule',
    settings: [],
  },
  {
    id: 'EMPTY_COMMAND',
    displayName: 'Remove standalone empty commands',
    description: 'Currently removes standalone punctuation-only command lines while retaining trailing quote comments.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'EmptyCommandRule',
    settings: [],
  },
  {
    id: 'ADD_TO_ETC',
    displayName: 'Replace obsolete ADD TO etc. with calculation assignment',
    description: 'Currently converts simple one-line ADD, SUBTRACT, MULTIPLY, and DIVIDE statements; requires ABAP 7.54 or later.',
    groupId: 'SYNTAX',
    defaultEnabled: false,
    essentialEnabled: true,
    docId: 'AddToEtcRule',
    minimumAbapRelease: 754,
    settings: [],
  },
  {
    id: 'RAISE_TYPE',
    displayName: 'Replace RAISE TYPE with RAISE NEW',
    description: 'Currently converts simple one-line RAISE EXCEPTION TYPE and RAISE SHORTDUMP TYPE statements; requires ABAP 7.52 or later.',
    groupId: 'SYNTAX',
    defaultEnabled: false,
    essentialEnabled: true,
    docId: 'RaiseTypeRule',
    minimumAbapRelease: 752,
    settings: [],
  },
  {
    id: 'CREATE_OBJECT',
    displayName: 'Replace CREATE OBJECT with NEW constructor',
    description: 'Currently converts simple one-line static CREATE OBJECT statements without parameters; requires ABAP 7.40 or later.',
    groupId: 'SYNTAX',
    defaultEnabled: false,
    essentialEnabled: true,
    docId: 'CreateObjectRule',
    minimumAbapRelease: 740,
    settings: [],
  },
  {
    id: 'MOVE_TO',
    displayName: 'Replace obsolete MOVE TO with =',
    description: 'Currently converts simple one-line MOVE source TO destination statements.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'MoveToRule',
    settings: [],
  },
  {
    id: 'CALCULATION_ASSIGNMENT',
    displayName: 'Prefer calculation assignment operators',
    description: 'Currently converts direct one-line identifier = identifier operator value assignments; requires ABAP 7.54 or later.',
    groupId: 'SYNTAX',
    defaultEnabled: false,
    essentialEnabled: false,
    docId: 'CalculationAssignmentRule',
    minimumAbapRelease: 754,
    settings: [],
  },
  {
    id: 'ASSERT_EQUALS_SUBRC',
    displayName: 'Use assert_subrc instead of assert_equals',
    description: 'Currently simplifies one-line assert_equals calls with exactly act = sy-subrc and a simple numeric exp value.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'AssertEqualsSubrcRule',
    settings: [],
  },
  {
    id: 'ASSERT_EQUALS_BOOLEAN',
    displayName: 'Use assert_true and assert_false',
    description: 'Currently simplifies one-line assert_equals calls with exactly act and boolean exp parameters, including nested functional act expressions.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'AssertEqualsBooleanRule',
    settings: [],
  },
  {
    id: 'CALL_METHOD',
    displayName: 'Replace CALL METHOD with functional call',
    description: 'Currently modernizes simple one-line static calls with existing or empty argument lists.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'CallMethodRule',
    settings: [],
  },
  {
    id: 'EXPORTING_KEYWORD',
    displayName: 'Omit optional EXPORTING',
    description: 'Currently removes EXPORTING from simple single-line method calls with no other sections.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'ExportingKeywordRule',
    settings: [],
  },
  {
    id: 'COMPARISON_OPERATOR',
    displayName: 'Use consistent set of comparison operators',
    description: 'Currently converts textual operators in simple logical control statements.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'ComparisonOperatorRule',
    settings: [],
  },
  {
    id: 'NOT_IS',
    displayName: 'Prefer IS NOT to NOT IS',
    description: 'Transforms simple single-line NOT operand IS predicates.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'NotIsRule',
    settings: [],
  },
  {
    id: 'LOGICAL_OPERATOR_POSITION',
    displayName: 'Move AND/OR etc. from line end to next line start',
    description: 'Currently moves terminal AND, OR, EQUIV, and selected LOOP or DELETE WHERE keywords to the next line.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: false,
    docId: 'LogicalOperatorPositionRule',
    settings: [],
  },
  {
    id: 'SELF_REFERENCE_ME',
    displayName: 'Remove the self-reference me->',
    description: 'Currently removes attached me-> only from direct method calls, never from attribute access.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'SelfReferenceMeRule',
    settings: [],
  },
  {
    id: 'READ_TABLE',
    displayName: 'Replace READ TABLE with table expression',
    description: 'Currently replaces simple one-line READ TABLE WITH KEY ... ASSIGNING statements with ASSIGN table expressions.',
    groupId: 'COMMANDS',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'ReadTableRule',
    minimumAbapRelease: 740,
    settings: [],
  },
  {
    id: 'VALUE_STATEMENT',
    displayName: 'Shorten VALUE statements',
    description: 'Currently factors one shared scalar assignment from exactly two simple one-line VALUE rows.',
    groupId: 'SYNTAX',
    defaultEnabled: false,
    essentialEnabled: false,
    docId: 'ValueStatementRule',
    minimumAbapRelease: 740,
    settings: [],
  },
  {
    id: 'INSET',
    displayName: 'Indent lines',
    description: 'Currently reindents the leading line of each recognized command (and its attached leading comments) to match IF/CASE/DO/WHILE/LOOP/TRY/SELECT/PROVIDE and CLASS/INTERFACE/METHOD/FORM/FUNCTION nesting depth; leaves chained same-line statements and multi-line continuation lines untouched.',
    groupId: 'PRETTY_PRINTER',
    defaultEnabled: true,
    essentialEnabled: true,
    docId: 'IndentRule',
    settings: [],
  },
];