import type { RuleMetadata } from '../../api.js';

export const SYNTAX_RULES: readonly RuleMetadata[] = [
  {
    id: 'CAMEL_CASE_IN_CDS_TEST',
    displayName: 'Use CamelCase in test class for CDS view',
    description: 'Currently adds CI_NOWHERE only to exact SELECT statements of the annotated CDS test view.',
    groupId: 'PRETTY_PRINTER',
    defaultEnabled: false,
    settings: [],
  },
  {
    id: 'IF_BLOCK_AT_LOOP_END',
    displayName: 'Replace long IF blocks at loop end',
    description: 'Currently converts a final single-command IF operand IS INITIAL loop block to an early CONTINUE guard.',
    groupId: 'COMMANDS',
    defaultEnabled: false,
    settings: [],
  },
  {
    id: 'IF_BLOCK_AT_METHOD_END',
    displayName: 'Replace long IF blocks at method end',
    description: 'Currently converts a final single-command IF operand IS INITIAL block to an early RETURN guard.',
    groupId: 'COMMANDS',
    defaultEnabled: false,
    settings: [],
  },
  {
    id: 'UPPER_AND_LOWER_CASE',
    displayName: 'Convert upper and lower case',
    description: 'Currently uppercases only recognized standalone statement-leading keywords.',
    groupId: 'PRETTY_PRINTER',
    defaultEnabled: false,
    settings: [],
  },
  {
    id: 'COMMENT_TYPE',
    displayName: 'Comment with " instead of * for prose',
    description: 'Currently converts only unambiguous column-one prose asterisk comments and preserves code-shaped comments.',
    groupId: 'SYNTAX',
    defaultEnabled: false,
    settings: [],
  },
  {
    id: 'CONDENSE',
    displayName: 'Replace CONDENSE with string function',
    description: 'Currently replaces adjacent declared scalar CONDENSE statements.',
    groupId: 'COMMANDS',
    defaultEnabled: false,
    minimumAbapRelease: 702,
    settings: [],
  },
  {
    id: 'STRING_TEMPLATE',
    displayName: 'Use string templates to assemble text',
    description: 'Currently converts safe backtick literal and identifier concatenations in simple assignments.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    minimumAbapRelease: 702,
    settings: [],
  },
  {
    id: 'ASSERT_PARAMETER_ORDER',
    displayName: 'Standardize assertion parameter order',
    description: 'Currently places EXP before ACT in two-argument scalar assert_equals calls.',
    groupId: 'COMMANDS',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'ASSERT_CLASS',
    displayName: 'Use assert class instead of ASSERT',
    description: 'Currently converts simple one-line bound, initial, scalar comparison, ABAP boolean, and sy-subrc ASSERT predicates to a configurable assert class.',
    groupId: 'COMMANDS',
    defaultEnabled: false,
    settings: [{ name: 'assertClassName', description: 'Class called for converted assertions.', type: 'string', defaultValue: 'cx_assert' }],
  },
  {
    id: 'DESCRIBE_TABLE',
    displayName: 'Replace DESCRIBE TABLE ... LINES with lines( )',
    description: 'Currently replaces exact uncommented DESCRIBE TABLE ... LINES statements immediately before RETURN.',
    groupId: 'COMMANDS',
    defaultEnabled: false,
    settings: [],
  },
  {
    id: 'TRANSLATE',
    displayName: 'Replace TRANSLATE with string functions',
    description: 'Currently replaces adjacent declared scalar TRANSLATE ... TO UPPER or LOWER CASE statements.',
    groupId: 'COMMANDS',
    defaultEnabled: false,
    minimumAbapRelease: 702,
    settings: [],
  },
  {
    id: 'TYPO',
    displayName: 'Correct frequent typos',
    description: 'Currently corrects an embedded unambiguous subset of frequent typos in comments only.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'NEEDLESS_PARENTHESES',
    displayName: 'Remove needless parentheses',
    description: 'Currently removes one outer pair around single-line operand IS INITIAL predicates in selected logical statements.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'PRAGMA_POSITION',
    displayName: 'Move pragmas to correct position',
    description: 'Currently moves one complete, uncommented trailing pragma before a statement period.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'END_OF_COMMENT',
    displayName: 'Remove end-of comments',
    description: 'Currently removes trailing METHOD, FORM, and FUNCTION end comments that exactly repeat the paired name.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'CHECK_IN_LOOP',
    displayName: 'Convert CHECK in loop to IF NOT ... CONTINUE',
    description: 'Currently converts single-line operand IS INITIAL checks in complete LOOP, DO, and WHILE blocks.',
    groupId: 'COMMANDS',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'CHECK_OUTSIDE_LOOP',
    displayName: 'Convert CHECK outside loop to IF NOT ... RETURN',
    description: 'Currently converts single-line operand IS INITIAL checks in complete procedures when no loop encloses them.',
    groupId: 'COMMANDS',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'EXIT_OUTSIDE_LOOP',
    displayName: 'Replace EXIT outside loop with RETURN',
    description: 'Currently converts bare EXIT statements inside complete methods, functions, and forms when no loop encloses them.',
    groupId: 'COMMANDS',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'EQUALS_SIGN_CHAIN',
    displayName: 'Resolve equals sign chain into several commands',
    description: 'Currently splits one-line chains of plain identifiers with a simple final value.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'PSEUDO_COMMENT',
    displayName: 'Replace obsolete pseudo comments with pragmas',
    description: 'Currently converts an embedded unambiguous subset of complete trailing pseudo-comments; requires ABAP 7.02 or later.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    minimumAbapRelease: 702,
    settings: [],
  },
  {
    id: 'RECEIVING_KEYWORD',
    displayName: 'Omit RECEIVING',
    description: 'Currently converts simple one-line method calls with only a simple RECEIVING parameter.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'EMPTY_COMMAND',
    displayName: 'Remove standalone empty commands',
    description: 'Currently removes standalone punctuation-only command lines while retaining trailing quote comments.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'ADD_TO_ETC',
    displayName: 'Replace obsolete ADD TO etc. with calculation assignment',
    description: 'Currently converts simple one-line ADD, SUBTRACT, MULTIPLY, and DIVIDE statements; requires ABAP 7.54 or later.',
    groupId: 'SYNTAX',
    defaultEnabled: false,
    minimumAbapRelease: 754,
    settings: [],
  },
  {
    id: 'RAISE_TYPE',
    displayName: 'Replace RAISE TYPE with RAISE NEW',
    description: 'Currently converts simple one-line RAISE EXCEPTION TYPE and RAISE SHORTDUMP TYPE statements; requires ABAP 7.52 or later.',
    groupId: 'SYNTAX',
    defaultEnabled: false,
    minimumAbapRelease: 752,
    settings: [],
  },
  {
    id: 'CREATE_OBJECT',
    displayName: 'Replace CREATE OBJECT with NEW constructor',
    description: 'Currently converts simple one-line static CREATE OBJECT statements without parameters; requires ABAP 7.40 or later.',
    groupId: 'SYNTAX',
    defaultEnabled: false,
    minimumAbapRelease: 740,
    settings: [],
  },
  {
    id: 'MOVE_TO',
    displayName: 'Replace obsolete MOVE TO with =',
    description: 'Currently converts simple one-line MOVE source TO destination statements.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'CALCULATION_ASSIGNMENT',
    displayName: 'Prefer calculation assignment operators',
    description: 'Currently converts direct one-line identifier = identifier operator value assignments; requires ABAP 7.54 or later.',
    groupId: 'SYNTAX',
    defaultEnabled: false,
    minimumAbapRelease: 754,
    settings: [],
  },
  {
    id: 'ASSERT_EQUALS_SUBRC',
    displayName: 'Use assert_subrc instead of assert_equals',
    description: 'Currently simplifies one-line assert_equals calls with exactly act = sy-subrc and a simple numeric exp value.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'ASSERT_EQUALS_BOOLEAN',
    displayName: 'Use assert_true and assert_false',
    description: 'Currently simplifies one-line assert_equals calls with exactly act and boolean exp parameters, including nested functional act expressions.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'CALL_METHOD',
    displayName: 'Replace CALL METHOD with functional call',
    description: 'Currently modernizes simple one-line static calls with existing or empty argument lists.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'EXPORTING_KEYWORD',
    displayName: 'Omit optional EXPORTING',
    description: 'Currently removes EXPORTING from simple single-line method calls with no other sections.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'COMPARISON_OPERATOR',
    displayName: 'Use consistent set of comparison operators',
    description: 'Currently converts textual operators in simple logical control statements.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'NOT_IS',
    displayName: 'Prefer IS NOT to NOT IS',
    description: 'Transforms simple single-line NOT operand IS predicates.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'LOGICAL_OPERATOR_POSITION',
    displayName: 'Move AND/OR etc. from line end to next line start',
    description: 'Currently moves terminal AND, OR, EQUIV, and selected LOOP or DELETE WHERE keywords to the next line.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'SELF_REFERENCE_ME',
    displayName: 'Remove the self-reference me->',
    description: 'Currently removes attached me-> only from direct method calls, never from attribute access.',
    groupId: 'SYNTAX',
    defaultEnabled: true,
    settings: [],
  },
  {
    id: 'READ_TABLE',
    displayName: 'Replace READ TABLE with table expression',
    description: 'Currently replaces simple one-line READ TABLE WITH KEY ... ASSIGNING statements with ASSIGN table expressions.',
    groupId: 'COMMANDS',
    defaultEnabled: true,
    minimumAbapRelease: 740,
    settings: [],
  },
  {
    id: 'VALUE_STATEMENT',
    displayName: 'Shorten VALUE statements',
    description: 'Currently factors one shared scalar assignment from exactly two simple one-line VALUE rows.',
    groupId: 'SYNTAX',
    defaultEnabled: false,
    minimumAbapRelease: 740,
    settings: [],
  },
];